name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu:22.04

    steps:
      - uses: actions/checkout@v3


      - name: Deploy
        run: |
          pkill -f "uvicorn" || true
          ssh -i ~/.ssh/id_ed25519 root@212.116.115.5 << 'EOF'
            cd /root/project/task-planner-app
            git pull origin main
            source /root/myvenv/bin/activate
            python3 -m backend.app.main
          EOF
