name: Deploy FastAPI to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: "just-a-placeholder"

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
            cd /home/task-planner-app
            
            git pull origin main

            cd backend
            
            source venv/bin/activate
            
            pip install -r requirements.txt
            
            cd ..

            python3 -m backend.app.main
          "
